-- Task 1: Retrieve customer information with the total number of orders

    SELECT Customers.name AS customer_name, COUNT(Orders.order_id) AS total_orders
    FROM Customers
    LEFT JOIN Orders ON Customers.customer_id = Orders.customer_id
    GROUP BY Customers.customer_id, Customers.name
    ORDER BY total_orders DESC;


--Task 2: Retrieve product name, quantity, and total amount for each order item

    SELECT Products.name AS product_name, Order_Items.quantity, (Order_Items.quantity * Order_Items.unit_price) AS total_amount
    FROM Order_Items
    JOIN Products ON Order_Items.product_id = Products.product_id
    ORDER BY Order_Items.order_item_id ASC;

--Task 3: Retrieve total revenue generated by each product category

    SELECT Categories.name AS category_name, SUM(Order_Items.quantity * Order_Items.unit_price) AS total_revenue
    FROM Categories
    LEFT JOIN Products ON Categories.category_id = Products.category_id
    LEFT JOIN Order_Items ON Products.product_id = Order_Items.product_id
    GROUP BY Categories.category_id, Categories.name
    ORDER BY total_revenue DESC;

--Task 4: Retrieve the top 5 customers with the highest total purchase amount

    SELECT Customers.name AS customer_name, SUM(Order_Items.quantity * Order_Items.unit_price) AS total_purchase_amount
    FROM Customers
    LEFT JOIN Orders ON Customers.customer_id = Orders.customer_id
    LEFT JOIN Order_Items ON Orders.order_id = Order_Items.order_id
    GROUP BY Customers.customer_id, Customers.name
    ORDER BY total_purchase_amount DESC
    LIMIT 5;